### ISSUE TITLE
Plugin is not functioning

### ISSUE THREAD

**Issue by zelenove** [Rahmon/woo-for-logged-users#10]
Using wordpress version 5.7.1, plugin does not appear to be functioning. Users who are not logged in can still see product page. Additionally, settings page in Wordpress dashboard displays error message: "Something went wrong. It wasn't possible to load the settings."

**Comment by Rahmon** [comment]
Hi @zelenove .

Testing in version 5.7.2 and it's working as expected. Could you provide more information about your environment?
