### ISSUE TITLE
Settings page not visible

### ISSUE THREAD

**Issue by FrankWalle** [Rahmon/woo-for-logged-users#37]
Hi.
I installed the plugin and if I go to Woocommerce > Woocommerce for logged users... there is only a blank page.
System: 
WP 6.7
Woo 9.4.1
Elementor 3.25.7

Any idea?
Thanks
Frank

**Comment by Rahmon** [comment]
Hi @FrankWalle 

This issue was fixed in version 1.4.0: https://wordpress.org/support/topic/settings-not-visible-on-dashboard/#post-18183919
