### ISSUE TITLE
 register_rest_route was called incorrectly

### ISSUE THREAD

**Issue by homerjsim** [Rahmon/woo-for-logged-users#8]
Hello, 
I get the following error message.

`PHP Notice:  register_rest_route was called <strong>incorrectly</strong>. The REST API route definition for <code>wflu/v1/settings</code> is missing the required <code>permission_callback</code> argument. For REST API routes that are intended to be public, use <code>__return_true</code> as the permission callback. Please see <a href="https://wordpress.org/support/article/debugging-in-wordpress/">Debugging in WordPress</a> for more information. (This message was added in version 5.5.0.) in /srv/www/wordpress-one/public_html/wp-includes/functions.php on line 5311`

I am Using the neweset wordpress an woocommerce addon.

Can you fix this?

**Comment by Rahmon** [comment]
Hi @homerjsim 

Thank you for reporting. I'll look into that as soon as possible.

**Comment by Rahmon** [comment]
Hi @homerjsim .

I've fixed it. I'll close this issue but feel free to reopen or create a new one if necessary.
